### ISSUE TITLE
Useless word JanE or JANE

### ISSUE THREAD

**Issue by bq1028** [itechub/Jane#114]
Waste one's time to type jane or JANE, why?

**Comment by Octobug** [comment]
@bq1028 
Hi，我不是很明白你的意思，有什么意见可以直接说出来，能改进的我们一定会改 :-)

**Comment by Octobug** [comment]
HI @bq1028 ,
I'm sorry that I can't fully understand what you mean. Could you state it more clearly so that we could make it right if that is reasonable. :-)
